### ISSUE TITLE
Add support for macOS arm chips M1,2,3

### ISSUE THREAD

**Issue by the-code-samurai-97** [zaucy/rules_vulkan#28]
currently it supports only x86_64

**Comment by zaucy** [comment]
I haven't been working on these rules as of late and I do not have a mac. I'm happy to accept a PR for non-x86 macOS :)

**Comment by sibi-venti** [comment]
@zaucy currently i am using the local sdk with a toolchaim to use the sdk,
 let me check! 
I see the link for downloading sdk for windows and linux us from official website but for the mac it's different! May i know why?
Did you copy the binaries and made a zip ?

**Comment by the-code-samurai-97** [comment]
@zaucy currently i am using the local sdk with a toolchaim to use the sdk,
let me check!
I see the link for downloading sdk for windows and linux us from official website but for the mac it's different! May i know why?
Did you copy the binaries and made a zip ?

**Comment by zaucy** [comment]
that was added here https://github.com/zaucy/rules_vulkan/pull/9 by @Vertexwahn 

apparently the official links were 404ing. no idea if that's still the case.

**Comment by the-code-samurai-97** [comment]
@zaucy and @Vertexwahn I tried the patch method to hhtp_archive and it worked
```
diff --git a/repo.bzl b/repo.bzl
index 82f72a5..fbbc189 100644
--- a/repo.bzl
+++ b/repo.bzl
@@ -58,8 +58,8 @@ alias(
         "@bazel_tools//src/conditions:linux_x86_64": _linux_{targetVarName},
 
         # MacOS
-        #"@bazel_tools//src/conditions:darwin": _macos_{targetVarName},
-        "@bazel_tools//src/conditions:darwin_x86_64": _macos_{targetVarName},
+        "@bazel_tools//src/conditions:darwin": _macos_{targetVarName},
+        #"@bazel_tools//src/conditions:darwin_x86_64": _macos_{targetVarName},
     }}),
 )
 """.format(targetName = commonTarget, targetVarName = commonTargetVarName)
```
@Vertexwahn is there a reason you have commented out the just darwin and explicitly mentioned darwin_x86_64? if not i can create a PR for issue

**Comment by the-code-samurai-97** [comment]
<img width="1295" alt="Screenshot 2024-01-08 at 9 29 33 PM 7" src="https://github.com/zaucy/rules_vulkan/assets/77912970/c702079d-96db-452b-b900-3dc8a073e552">
glfw and vulkan example

**Comment by Vertexwahn** [comment]
@the-code-samurai-97 

> I see the link for downloading sdk for windows and linux us from official website but for the mac it's different! May i know why?
> Did you copy the binaries and made a zip ?

Initially for macOS a `tar.gz` was provided. This was switched to `*.dmg` file for newer versions of the Vulkan SDK provided by LunarXchange. Bazel does not provide any trivial built-in support for extracting `*.dmg` files. I know @zaucy has written some magic to extract also dmg files using Bazel, but I never found the time to adapt this for these rules. The easy workaround was to extract the content of the dmg and to tar it again. Not sure, If I kept only the x64 binaries or if it also contains arm64 M1 compatible binaries.

The clean approach here would be to extract dmg files directly via Bazel. Please note that Bazel is switching in the long term to [bzlmod](https://blog.bazel.build/2023/12/11/bazel-7-release.html#bzlmod). Unfortunately, this brings some changes of how artifacts are fetched (you have to introduce a module extension) - personally I would go with bzlmod.

> @Vertexwahn is there a reason you have commented out the just darwin and explicitly mentioned darwin_x86_64? if not i can create a PR for issue

I had some compile issue - but I can not remember exactly what was it about

`bazel query @bazel_tools//src/conditions:all` gives:

```
@bazel_tools//src/conditions:darwin
@bazel_tools//src/conditions:darwin_arm64
@bazel_tools//src/conditions:darwin_arm64e
@bazel_tools//src/conditions:darwin_x86_64
...
```

Maybe it make sense to differentiate between arm64 and x86_64 - not sure.

Looking forward to your PR!

**Comment by the-code-samurai-97** [comment]
@zaucy @Vertexwahn I can't push ! is there a settings i should check?, i created a separated branch to create a PR

**Comment by Vertexwahn** [comment]
@the-code-samurai-97 You have to fork this repo first - then you create a branch in your forked repo - then you initiate a pull request

**Comment by the-code-samurai-97** [comment]
@Vertexwahn Thanks! https://github.com/zaucy/rules_vulkan/pull/29
