### ISSUE TITLE
Vulkan SDK download does not work on macOS

### ISSUE THREAD

**Issue by Vertexwahn** [zaucy/rules_vulkan#6]
It seems there the Vulkan SDK is only available as` .dmg` - I created a ZIP file out if this is available here: https://vertexwahn.de/lfs/v1/vulkansdk-macos-1.2.162.1.zip

I am also not happy with the workaround but, this was the cheapest way to fix it for me

**Comment by zaucy** [comment]
Ah good to know. I've delt with this in rules_blender by [extracting it myself in the repository rule](https://github.com/zaucy/rules_blender/blob/main/repo.bzl#L531). I could do similar here.

Unfortunately I'm not using `rules_vulkan` in my current projects so I haven't had the motivation to update it recently. Contributions are always welcome!

**Comment by zaucy** [comment]
@Vertexwahn can this be closed now that #10 is merged?
